swagger: "2.0"
info:
  description: "Test CORS"
  version: "1.0.0"
  title: "TEST CORS"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "apiteam@swagger.io"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "salty-reaches-39641.herokuapp.com"
basePath: "/"
schemes:
- "https"
paths:
  /return:
    get:
      summary: "Return code as status"
      description: ""
      operationId: "addPet"
      consumes:
      - "application/json"
      - "application/xml"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - in: "query"
        name: "code"
        description: "Code to return"
        required: true
        type: "string"
      responses:
        405:
          description: "Only error in spec"
          schema:
            type: "string"